#! /usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")"

if [ -n "$1" ]; then
	stackName="$1"

	eval "$(./manage-stack -s "${stackName}" config)"
	export REGISTRY WAVELET_TAG
fi

cd nodes
for dir in */; do
	(
		set -e

		cd "${dir}"
		./build.sh
	)
done
