#! /usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")"

args=()
if [ -n "$1" ]; then
	stackName="$1"

	args+=(-s "${stackName}")
fi

eval "$(./manage-stack "${args[@]}" config)"
export REGISTRY WAVELET_TAG

cd nodes
for dir in */; do
	(
		set -e

		cd "${dir}"
		./build.sh
	)
done
