#! /usr/bin/env bash

if [ ! -x "$(command -v docker-machine)" ]; then
	echo "\"docker-machine\" is required, but missing" >&2

	exit 1
fi

if [ ! -x "$(command -v docker)" ]; then
	echo "\"docker\" is required, but missing" >&2

	exit 1
fi

function create_digitalocean() {
	local name token count
	local idx
	local pids
	local node1 ip
	local arg nextArg docker_machine_args

	name="$1"
	token="$2"
	count='3'
	shift; shift;

	if [ -z "${name}" -o -z "${token}" ]; then
		echo "Usage: manage-swarm create digitalocean <swarmName> <apiToken> [--count <n>]" >&2
		echo "                    [--size <n>] [--region <name>]" >&2

		return 1
	fi

	docker_machine_args=()

	nextArg=''
	docker_machine_args=(
		--digitalocean-tags "docker-swarm,${name}"
	)
	for arg in "$@"; do
		if [ -n "${nextArg}" ]; then
			if [ "${nextArg}" = '+' ]; then
				docker_machine_args+=("${arg}")
			else
				eval "${nextArg}="'"${arg}"'
			fi
			nextArg=''
			continue
		fi
		case "${arg}" in
			--size|--region)
				docker_machine_args+=("--digitalocean-${arg:2}")
				nextArg='+'
				;;
			--count)
				nextArg='count'
				;;
		esac
	done

	pids=()
	for ((idx = 1; idx <= count; idx++)) {
		docker-machine create --driver digitalocean --digitalocean-access-token "${token}" "${docker_machine_args[@]}" "${name}-${idx}" &
		pids+=("$!")
	}
	wait "${pids[@]}"

	node1="${name}-1"
	ip="$(docker-machine inspect "${node1}" | jq -crM .Driver.IPAddress)" || return 1
	docker-machine ssh "${node1}" docker swarm init --advertise-addr "${ip}" || return 1

	joinCommand="$(docker-machine ssh "${node1}" docker swarm join-token worker | grep ' --token ')"
	for ((idx = 2; idx <= count; idx++)) {
		docker-machine ssh "${name}-${idx}" "${joinCommand}" || return 1
	}

	mkdir -p "${swarmEnvDir}"
	docker-machine env "${name}-1" > "${swarmEnvDir}/${name}"

	return 0
}

function create() {
	local provider
	local swarmFile

	provider="$1"
	name="$2"
	shift

	if [ -z "${provider}" ]; then
		echo "Usage: manage-swarm create <provider> <swarmName> ..." >&2

		return 1
	fi

	swarmFile="${swarmEnvDir}/${name}"

	if [ -n "${name}" -a -f "${swarmFile}" ]; then
		echo "Swarm already exists: ${swarmFile}" >&2

		return 1
	fi

	create_${provider} "$@" || return "$?"

	exportConfigToSwarm "${name}"

	return 0
}

function destroy() {
	local name
	local swarmFile

	name="$1"

	if [ -z "${name}" ]; then
		echo "Usage: manage-swarm destroy <swarmName>" >&2

		return 1
	fi

	swarmFile="${swarmEnvDir}/${name}"
	if [ ! -f "${swarmFile}" ]; then
		echo "Swarm does not exist: ${swarmFile}" >&2

		return 1
	fi

	(
		. "${swarmFile}"
		toDelete=( $(
			docker node ls -q | while IFS='' read -r id; do
				machine="$(docker node inspect "${id}" | jq -crM '.[0].Description.Hostname')"
				echo "${machine}"
			done
		) )

		retval='0'
		for machine in "${toDelete[@]}"; do
			docker-machine rm --force "${machine}" || retval='1'
		done

		exit "${retval}"
	) || return 1

	rm -f "${swarmFile}"

	return 0
}

function status() {
	local name
	local swarmFile

	name="$1"

	if [ -z "${name}" ]; then
		echo "Usage: manage-swarm status <swarmName>" >&2

		return 1
	fi

	swarmFile="${swarmEnvDir}/${name}"
	if [ ! -f "${swarmFile}" ]; then
		echo "Swarm does not exist: ${swarmFile}" >&2

		return 1
	fi

	(
		. "${swarmFile}"
		docker node ls
		docker stack ls
	) || return 1

	return 0
}

function list() {
	local file

	cd "${swarmEnvDir}" 2>/dev/null || return 0
	for file in *; do
		if [ ! -s "${file}" ]; then
			continue
		fi

		echo "${file}"
	done

	return 0
}

function exportConfigToSwarm() {
	local name
	local swarmFile
	local tmpdir
	local retval

	name="$1"

	if [ -z "${name}" ]; then
		echo "Usage: exportConfigToSwarm <swarmName>" >&2

		return 1
	fi

	swarmFile="${swarmEnvDir}/${name}"
	if [ ! -f "${swarmFile}" ]; then
		echo "Swarm does not exist: ${swarmFile}" >&2

		return 1
	fi

	tmpdir="$(mktemp -d)" || return 1
	tarfile="$(mktemp)" || return 1

	(
		. "${swarmFile}"

		dockerMachineBaseDir="${HOME}/.docker/machine/machines"
		docker node ls --format '{{.Hostname}}' | while IFS='' read -r hostname; do
			dockerMachineDir="${dockerMachineBaseDir}/${hostname}"
			configDir="${tmpdir}/${hostname}"

			cp -rp "${dockerMachineDir}" "${configDir}"
			cp "${dockerMachineBaseDir}/../certs/key.pem" "${configDir}/key.pem"
			cp "${dockerMachineBaseDir}/../certs/cert.pem" "${configDir}/cert.pem"
			cp "${dockerMachineBaseDir}/../certs/ca.pem" "${configDir}/ca.pem"
			cp "${dockerMachineBaseDir}/../certs/ca-key.pem" "${configDir}/ca-key.pem"

			cat "${configDir}/config.json" | sed '
				s|"/.*/\.docker/machine/machines/'"${hostname}"'\(/*\)|"@DOCKER_MACHINE_DIR@\1|g
				s|"/.*/\.docker/machine/certs/key\.pem"|"@DOCKER_MACHINE_DIR@/key.pem"|g
				s|"/.*/\.docker/machine/certs/cert\.pem"|"@DOCKER_MACHINE_DIR@/cert.pem"|g
				s|"/.*/\.docker/machine/certs/ca\.pem"|"@DOCKER_MACHINE_DIR@/ca.pem"|g
				s|"/.*/\.docker/machine/certs/ca-key\.pem"|"@DOCKER_MACHINE_DIR@/ca-key.pem"|g
				s|"/.*/\.docker/machine/certs"|"@DOCKER_MACHINE_DIR@"|g
				s|"/.*/\.docker/machine"|"@DOCKER_MACHINE_DIR@/../.."|g
			' > "${configDir}/config.json.in"
			rm -f "${configDir}/config.json"
		done

		(
			set -e

			cd "${tmpdir}"
			tar -cf - * | gzip -9c > "${tarfile}"
			gzip -dc "${tarfile}" | tar -tf - >/dev/null
		) || exit 1

		docker node ls --format '{{.Hostname}}' | while IFS='' read -r hostname; do
			docker-machine scp "${tarfile}" "${hostname}:/etc/wavelet-swarm.tar.gz" </dev/null
		done
	)
	retval="$?"

	rm -rf "${tmpdir}"
	rm -f "${tarfile}"

	return "${retval}"
}

function import() {
	local ip
	local swarmFile swarmName
	local tmpdir
	local retval

	ip="$1"

	if [ -z "${ip}" ]; then
		echo "Usage: manage-swarm import <ip>" >&2

		return 1
	fi

	tmpdir="$(mktemp -d)" || return 1

	(
		set -e

		dockerMachineBaseDir="${HOME}/.docker/machine/machines"
		mkdir -p "${dockerMachineBaseDir}"

		cd "${tmpdir}"

		scp "root@${ip}:/etc/wavelet-swarm.tar.gz" wavelet-swarm.tar.gz

		gzip -dc wavelet-swarm.tar.gz | tar -xf - >/dev/null
		rm -f wavelet-swarm.tar.gz

		for hostname in *; do
			dockerMachineDir="${dockerMachineBaseDir}/${hostname}"
			if [ -d "${dockerMachineDir}" ]; then
				continue
			fi

			cp -rp "${hostname}" "${dockerMachineDir}/"
			sed "s|@DOCKER_MACHINE_DIR@|${dockerMachineDir}|g" "${dockerMachineDir}/config.json.in" > "${dockerMachineDir}/config.json"
			rm -f "${dockerMachineDir}/config.json.in"
		done
	)
	retval="$?"

	if [ "${retval}" = '0' ]; then
		swarmName="$(cd "${tmpdir}" && echo *-1 | sed 's@-1$@@')"
		swarmFile="${swarmEnvDir}/${swarmName}"

		mkdir -p "${swarmEnvDir}"
		docker-machine env "${swarmName}-1" > "${swarmFile}"
	fi

	rm -rf "${tmpdir}"

	return "${retval}"
}

function usage() {
	echo "Usage: manage-swarm create <provider> <swarmName> ..."
	echo "       manage-swarm import <ip>"
	echo "       manage-swarm destroy <swarmName>"
	echo "       manage-swarm status <swarmName>"
	echo "       manage-swarm list"
	echo "       manage-swarm help"
}

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

action="$1"
shift

configDir="$(dirname "${BASH_SOURCE[0]}")/config"
globalEnvFile="${configDir}/default"
if [ -f "${globalEnvFile}" ]; then
	. "${globalEnvFile}"
fi

swarmEnvDir="${configDir}/swarms"

case "${action}" in
	create|destroy|status|list|import|exportConfigToSwarm)
		"${action}" "$@"
		exit "$?"
		;;
	ls)
		list "$@"
		exit "$?"
		;;
	help)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
		;;
esac
